name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd client
        npm ci || npm install

    - name: Create package.json if not exists
      run: |
        if [ ! -f "client/package.json" ]; then
          cd client
          npm init -y
          npm install next react react-dom @types/react @types/node typescript
          npm install @stripe/stripe-js @stripe/react-stripe-js stripe
          npm install @radix-ui/react-icons lucide-react
          npm install tailwindcss postcss autoprefixer
          npm install @types/stripe
        fi

    - name: Build application
      run: |
        cd client
        npm run build || true
      env:
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

    - name: Check build output
      run: |
        cd client
        if [ -d ".next" ]; then
          echo "Build completed successfully"
        else
          echo "Build failed"
          exit 1
        fi
