name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for server
        run: |
          cd server
          npm install

      - name: Install dependencies for client
        run: |
          cd client
          npm install
